application: climb-comp
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

skip_files:
- ^src/.*  
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.application